apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: customer-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - image: jmezna/rso-customers:0.02
        name: customer
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-customers:5432/customer
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://169.51.13.134:32696
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
